config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :users, 

  	controllers: {
    	registrations: 'users/registrations',
      sessions: 'users/sessions',
    	confirmations: 'users/confirmations',
      passwords: 'users/passwords'
    
  	}


  	
  get 'general/deleteSessions' => 'general#deleteSessions', :as => "delete_all_sessions"
  get 'general/deleteSessionsV2' => 'general#deleteSessionsV2', :as => "delete_all_sessionsV2"
  get 'general/deleteSIps' => 'general#deleteIps', :as => "delete_all_ips"
  get 'video/index'
  get 'admins/index' => 'admins#index', :as =>'admins'
  root 'general#index'

  patch 'general/judge' => 'general#judge', :as => "judge"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admins/_cwa_logo_v3.html.erb
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="165 170 641 278" style="enable-background:new 165 170 641 278;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#EA2629;}
	.st1{enable-background:new;}
	.st2{fill:#FFFFFF;}
</style>
<path class="st0" d="M800.3,299.1c-0.7,0.5-1.7,0.6-2.9,0.6c-18.5,0-37,0-55.6,0c-1.2,0-1.7-0.1-1.9-0.8c-2.7-6.1-5.5-12.3-8.2-18.5
	c-0.2-0.4-0.5-0.6-1.3-0.6c-19.9,0-39.9,0-59.8,0c-0.3,0-0.6,0-1,0c-2.9,6.6-5.8,13.1-8.7,19.8c-0.5,0-0.9,0-1.4,0
	c-18.4,0-36.7,0-55.1,0c-1.8,0-2.3-0.3-1.8-1.2c10.7-19,21.4-37.9,32.2-56.9c11.7-20.7,23.4-41.4,35-62c0.3-0.6,0.8-0.8,1.9-0.8
	c19.7,0,39.5,0,59.2,0c1.1,0,1.6,0.2,1.8,0.7c9,16,18.1,32,27.1,48.1c8,14.3,16.1,28.5,24.1,42.7c5.3,9.4,10.6,18.8,15.9,28.1
	c0.1,0.2,0.3,0.4,0.5,0.6C800.3,299,800.3,299.1,800.3,299.1z M719.3,253c-6.2-13.4-12.4-26.8-18.6-40.1c-0.1,0-0.2,0-0.3,0
	c-6.1,13.4-12.3,26.8-18.4,40.1C694.6,253,706.8,253,719.3,253z"/>
<path class="st0" d="M273.2,175.4c2,0.1,3.9,0.3,5.9,0.4c14.8,1,28.3,3.5,39.5,8.7c7.3,3.4,12.9,7.4,17.4,11.8
	c5.5,5.3,9.2,10.9,12.1,16.6c0.1,0.1,0.1,0.3,0.1,0.5c-3.3,0.5-6.5,1-9.7,1.5c-13.1,1.9-26.1,3.8-39.2,5.8c-1.6,0.3-2.1,0.1-2.5-0.8
	c-1.4-2.7-2.8-5.4-5.7-7.9c-3.6-3-8.1-5.5-14.7-7c-10-2.2-22.4-1-30.2,2.9c-6.4,3.1-10.1,7.1-12.3,11.4c-1.8,3.4-2.8,7-3.1,10.5
	c-0.3,4-0.5,8-0.4,12c0.2,5.7,1.2,11.4,4.2,17c1.8,3.4,4.8,6.4,9.8,8.9s11.1,3.7,18.1,3.9c5.4,0.1,10.7-0.3,15.5-1.5
	c4.6-1.2,7.9-3,10.5-5.2c4.2-3.5,6.7-7.4,8.6-11.4c0.6-1.4,1.1-2.8,1.7-4.2c0.3-0.8,1-1,2.5-0.7c12.9,2.6,25.7,5.1,38.6,7.8
	c3,0.6,6,1.2,9,1.8c0.7,0.1,0.9,0.3,0.8,0.6c-3.6,9.5-9.1,18.6-20.5,26.6c-8.2,5.8-18.5,10.1-31.9,12.6c-6.5,1.2-13.3,1.8-20.2,2.1
	c-7.2,0.3-14.4,0.3-21.6,0c-13.4-0.6-26.2-2.1-37.7-5.8c-8.4-2.6-15-6.2-20.6-10.3c-10.6-7.6-17.5-16-21-25.1
	c-2.1-5.6-3.3-11.1-3.6-16.8c0-0.1-0.1-0.4-0.2-0.5c0-2.8,0-5.4,0-8.2c0.1-0.1,0.2-0.3,0.2-0.5c0.2-4,0.9-8,1.9-11.9
	c1.5-5.7,4-11.2,7.9-16.5c4.9-6.7,11.9-12.8,22-17.8c12.7-6.4,28.3-9.9,46.1-11c1.8-0.1,3.6-0.3,5.4-0.4
	C261.8,175.4,267.5,175.4,273.2,175.4z"/>
<path class="st0" d="M172.2,304.8c0.4,0,0.9,0,1.3,0c33.5,0,66.9,0,100.4,0.4c4.1,0,8.2,0,12.4,0c22.6,0,45.3,0.4,67.9,0.4
	c11,0,22,0,33,0c33.2,0,66.3,0,99.5,0c21.8,0,43.6,0,65.4,0.4c22.2,0,44.5,0.4,66.7,0.4c10.2,0,20.3,0,30.5,0c34.4,0,68.8,0,103.3,0
	c15.2,0,30.5,0,45.7,0.4c0.4,0,0.9,0,1.4,0c0,44.9,0,89,0,134.3c-0.4,0-0.8,0-1.3,0c-16.4,0-32.8,0-49.3,0c-21.2,0-42.4,0-63.5-0.4
	c-23,0-45.9-0.4-68.9-0.4c-9.6,0-19.2,0-28.8,0c-34.3,0-68.5,0-102.8,0c-22,0-44.1,0-66.1-0.4c-22.3,0-44.6-0.4-67-0.4
	c-14.5,0-29,0-43.5,0c-29.7,0-59.5,0-89.2,0c-15.1,0-30.3,0-45.4,0c-0.5,0-1,0.4-1.5,0.4C172.2,394.6,172.2,349.7,172.2,304.8z"/>
<path class="st0" d="M412.9,177.3c6.1,21.5,12.2,42.9,18.3,64.3c0.1,0,0.2,0,0.3,0c0.7-1.6,1.3-3.1,2-4.8c3.1-7.4,6.1-14.7,9.2-22.1
	c3.5-8.4,6.9-16.6,10.4-25c1.7-4,3.3-8,5-12c0.2-0.4,0.5-0.5,1.3-0.5c17.4,0,34.8,0,52.2,0c0.8,0,1.1,0.2,1.2,0.5
	c4.5,10.9,9,21.8,13.6,32.6c4,9.6,8,19.2,12,28.8c0.3,0.8,0.6,1.6,1.2,2.4c0.3-1.1,0.7-2.3,1-3.5c1.1-3.8,2.2-7.6,3.3-11.4
	c1.2-4.3,2.4-8.6,3.7-13c1.2-4,2.3-8.1,3.5-12.1c1.2-4.3,2.4-8.6,3.7-13c1-3.6,2.1-7.3,3.1-10.9c0.1-0.3,0.3-0.5,1-0.4
	c0.2,0,0.5,0,0.7,0c16.8,0,33.6,0,50.4,0c2.1,0,2.5,0.3,2.1,1.3c-1.6,4.6-3.1,9.4-4.6,14s-3.1,9.3-4.6,14
	c-1.7,5.1-3.4,10.3-5.1,15.5c-1.8,5.4-3.6,10.8-5.4,16.1c-1.6,4.9-3.2,9.8-4.9,14.7c-1.8,5.4-3.5,10.7-5.3,16.1
	c-1.6,4.9-3.3,9.9-4.9,14.8c-1.5,4.6-3,9.2-4.6,13.8c-0.1,0.1-0.2,0.3-0.3,0.5c-0.4,0-0.9,0-1.3,0c-17.8,0-35.6,0-53.4,0
	c-1.1,0-1.5-0.1-1.7-0.7c-3.3-8.1-6.7-16.1-10.1-24.3c-3.1-7.4-6.2-14.9-9.3-22.3c-3.2-7.7-6.4-15.4-9.7-23.1c-0.4-1-0.8-2-1.5-3
	c-0.3,0.7-0.6,1.4-0.9,2.1c-3.8,9.1-7.6,18.1-11.4,27.3c-3.8,9.2-7.7,18.5-11.5,27.6c-2.2,5.3-4.4,10.6-6.6,15.8
	c-0.1,0.3-0.3,0.5-1,0.5c-18.3,0-36.6,0-54.8,0c-0.1,0-0.2,0-0.5-0.1c-0.4-1.1-0.8-2.3-1.2-3.4c-1.6-4.9-3.3-9.8-4.9-14.6
	s-3.3-9.8-4.9-14.6c-1.6-4.9-3.2-9.7-4.9-14.5c-1.7-5.1-3.4-10.3-5.1-15.4c-1.5-4.6-3.1-9.3-4.7-13.9c-1.5-4.6-3.1-9.3-4.6-13.9
	c-1.6-4.9-3.2-9.7-4.9-14.5c-1.5-4.6-3.1-9.3-4.6-13.9c-0.1-0.3-0.2-0.6-0.3-0.9c-0.3-0.9,0.2-1.2,2-1.2c12.6,0,25.1,0,37.7,0
	c4.4,0,8.9,0,13.3,0C411.9,177.3,412.4,177.3,412.9,177.3z"/>
<g class="st1">
	<path class="st2" d="M206.4,406v-76.5c0-3.8,3.1-6.9,6.9-6.9h10.3c3.8,0,6.9,3.1,6.9,6.8l0.3,62.8c0,3.8,3.1,6.8,6.9,6.8h65
		c1.4,0,2.7,0.4,3.8,1.2h0c5.6,3.8,3,12.6-3.8,12.6h-89.3C209.5,412.9,206.4,409.8,206.4,406z"/>
	<path class="st2" d="M326.4,329L326.4,329c0-3.5,2.2-6.4,5-6.4h13.4c2.7,0,5,2.9,5,6.4v0c0,3.5-2.2,6.4-5,6.4h-13.4
		C328.6,335.4,326.4,332.5,326.4,329z M326.4,406.5v-52.6c0-3.5,2.2-6.4,5-6.4h13.4c2.7,0,5,2.9,5,6.4v52.6c0,3.5-2.2,6.4-5,6.4
		h-13.4C328.6,412.9,326.4,410,326.4,406.5z"/>
	<path class="st2" d="M404.7,409.2L367.4,360c-3.6-4.8-0.2-11.6,5.8-11.6h0c2.3,0,4.5,1.1,5.9,3l29.3,40.9c0.2,0.3,0.5,0.6,0.8,0.9
		c1.1,1.1,2.2,2.2,3.3,3.4c2.8,3,7.5,3,10.4,0.1c1-1,2-2,3.2-3.1c0.2-0.2,0.3-0.3,0.5-0.5l36.3-42.2c1.4-1.6,3.4-2.5,5.5-2.5h2.7
		c6.3,0,9.6,7.5,5.3,12.2l-45.4,49.2c-1.4,1.5-3.3,2.3-5.3,2.3h-15C408.2,412.1,406.1,411,404.7,409.2z"/>
	<path class="st2" d="M588.9,390.9l17.3,1c2.5,0.1,3.6,3.1,2,4.9c-4.1,4.4-10,8-17.7,10.7c-10.3,3.6-23.4,5.4-39.4,5.4
		c-20.1,0-36.1-2.9-47.9-8.7c-11.8-5.8-17.7-13.9-17.7-24.3c0-10.8,6-19.2,17.9-25.1c11.9-6,27.4-8.9,46.4-8.9
		c18.4,0,33.5,2.9,45.1,8.8s17.5,14,17.5,24.6c0,0,0,0,0,0c0,1.6-1.3,2.9-2.9,2.9h-96.3c-2,0-3.4,2-2.8,3.9c1.8,5.2,5.7,9.3,12,12.3
		c7.7,3.7,17.3,5.6,28.8,5.6c8.6,0,15.9-1,21.9-3.1c5.5-1.9,10-4.9,13.5-8.9C587.1,391.2,588,390.8,588.9,390.9z M514.7,373.2h69
		c2.1,0,3.5-2.1,2.7-4c-1.5-3.4-4-6.1-7.6-8.1c-7.4-4.2-17.1-6.3-28.9-6.3c-10.7,0-19.7,1.7-27,5c-5.4,2.5-9,5.5-10.8,9.2
		C511.1,371,512.6,373.2,514.7,373.2z"/>
</g>
<circle class="st2" cx="710" cy="372.9" r="60.1"/>
<polygon class="st0" points="680.4,340.1 756.2,373.3 680,405.4 "/>
</svg>

app/views/admins/index.html.erb
<section id="admin_section">
	



<% if current_user.try(:admin?) %>

	

	<table>
	    <% @users.each do |user| %>

	      <tr>
	      	
	      	<td>

	    		<% if user.avatar.attached? && user.avatar.variable? %>

	    			<%= puts "user.avatar.attached = " + user.avatar.attached?.to_s %>
	    			<%= puts "user.avatar.varible = " + user.avatar.variable?.to_s %>

						
					<%= image_tag user.avatar.variant(resize_to_limit: [32, 32]) %>
						

				<% elsif user.avatar.attached? && user.avatar.previewable? %>
 
	    			<%= puts "no.avatar.attached = " + user.avatar.attached?.to_s %>
	    			<%= puts "no.avatar.varible = " + user.avatar.variable?.to_s %>

	    			<%= image_tag user.avatar.preview(resize_to_limit: [32, 32]) %>

    			<% else %>

					<%= image_tag("/assets/man100px.png", height: '32', width: '32') %>


				<% end %>

    		</td>
			
			<td><%= user.uid %></td>
			<td><%= user.first_name %></td>
        	<td><%= user.last_name %></td>

        	<% if user.approved? && !user.admin %>
				<td><%= link_to "click to ban", judge_path(:id => user.id, :approved => false), :method => :patch %>
				
				</td>
			<%elsif !user.approved && !user.admin  %>
				<td><%= link_to "click to approve user", judge_path(:id => user.id, :approved => true), :method => :patch %>
				
				</td>

			<%else user.admin %>
				<td><%= "admin account" %>
				
				</td>



			<%end%>

			<td><%= user.email%></td>
			<td><%= user.confirmation_sent_at%></td>
			<td><%= user.confirmed_at%></td>

			



				
	      
	      </tr>
	    

	    <% end %>
	</table>

	Total Users = <%= @users.count %>
<% end %>


<%= link_to delete_all_sessions_path do %>
	<div id="delete_all_sessions">DeleteAllSessions</div>
<% end %>

<%= link_to delete_all_ips_path do %>
	<div id="delete_all_ips">DeleteAllIps</div>
<% end %>

</section>